export enum CommunicationList {
    email,
    location_on,
    phone,
    business,
    chat,
    mail_outline,
    list_alt,
    vpn_key,
    alternate_email,
    subscriptions,
    carpenter,
    chair,
    electric_bolt,
    heat_pump,
    mic_none,
}